RABBIT_HOST=${RABBIT_HOST:-127.0.0.1}
RABBIT_PORT=${RABBIT_PORT:-15672}
RABBIT_USER=${RABBIT_USER:-guest}
RABBIT_PASSWORD=${RABBIT_PASSWORD:-guest}
RABBIT_VHOST=${RABBIT_VHOST:-/}

RABBIT_EXCHANGE=${RABBIT_EXCHANGE:-amq.default}
RABBIT_QUEUE=${RABBIT_QUEUE:-nap-tasks}
RABBIT_PAYLOAD=${RABBIT_PAYLOAD:-"{}"}

./rabbitmqadmin -H $RABBIT_HOST \
  -V $RABBIT_VHOST \
  -P $RABBIT_PORT \
  -u $RABBIT_USER \
  -p $RABBIT_PASSWORD \
  publish exchange="$RABBIT_EXCHANGE" \
  routing_key="$RABBIT_QUEUE" \
  payload="$@"
